# Generated by Django 2.2.2 on 2020-05-19 09:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='AlgoSequense',
            field=models.CharField(default='', max_length=10000),
            preserve_default=False,
        ),
    ]
